name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: docs
        cache: true
        python_version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install .[docs]
